[project]
name = "vanilla-vae"
version = "0.1.0"
description = "Vanilla VAE implementation"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "torch==2.8.0",
    "numpy",
    "torchvision",
    "matplotlib>=3.9.4",
    "torchmetrics>=1.8.2",
    "torch-fidelity>=0.3.0",
]

